# Generated by Django 2.2.15 on 2020-08-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_line',
            name='reduction_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_line',
            name='reduction_rate_no_prod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_line',
            name='reduction_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_line',
            name='type_free_product',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
