# Generated by Django 2.2.15 on 2020-08-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200824_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_line',
            name='type_free_product',
        ),
        migrations.AddField(
            model_name='order_line',
            name='no_buy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_line',
            name='no_free',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
